// <auto-generated />
using System;
using GraduateSolution.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduateSolution.Migrations
{
    [DbContext(typeof(foot_ball_sourceContext))]
    [Migration("20231221173245_InitialSchoolDB")]
    partial class InitialSchoolDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GraduateSolution.Models.Admin", b =>
                {
                    b.Property<string>("Maadmin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MAADMIN");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Tenadmin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENADMIN");

                    b.HasKey("Maadmin");

                    b.ToTable("ADMIN", (string)null);
                });

            modelBuilder.Entity("GraduateSolution.Models.Anh", b =>
                {
                    b.Property<string>("Maanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MAANH");

                    b.Property<string>("Hinhanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HINHANH");

                    b.Property<string>("Maadm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MAADM");

                    b.Property<string>("Matinbai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MATINBAI");

                    b.Property<string>("Noidung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOIDUNG");

                    b.Property<string>("Tenanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENANH");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Maanh");

                    b.ToTable("anh", (string)null);
                });

            modelBuilder.Entity("GraduateSolution.Models.DanhMuc", b =>
                {
                    b.Property<string>("Madm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MADM");

                    b.Property<string>("Mota")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tendm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENDM");

                    b.HasKey("Madm");

                    b.ToTable("danh_muc", (string)null);
                });

            modelBuilder.Entity("GraduateSolution.Models.DanhMucCon", b =>
                {
                    b.Property<string>("Madmc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MADMC");

                    b.Property<string>("Madm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MADM");

                    b.Property<string>("Mota")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tendmc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENDMC");

                    b.HasKey("Madmc");

                    b.ToTable("danh_muc_con", (string)null);
                });

            modelBuilder.Entity("GraduateSolution.Models.NguoiDung", b =>
                {
                    b.Property<string>("Manguoidung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MANGUOIDUNG");

                    b.Property<string>("Maadmin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MAADMIN");

                    b.Property<string>("Noidung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOIDUNG");

                    b.Property<string>("Tennguoidung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENNGUOIDUNG");

                    b.Property<string>("Tieude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TIEUDE");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Manguoidung")
                        .HasName("PK_Table_1");

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("GraduateSolution.Models.TinBai", b =>
                {
                    b.Property<string>("Matinbai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MATINBAI");

                    b.Property<string>("Maadm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MAADM");

                    b.Property<string>("Madm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MADM");

                    b.Property<string>("Madmc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MADMC");

                    b.Property<string>("Noidung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOIDUNG");

                    b.Property<string>("Tentinbai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENTINBAI");

                    b.Property<DateTime?>("Thoigiandang")
                        .HasColumnType("datetime")
                        .HasColumnName("THOIGIANDANG");

                    b.Property<string>("Tieude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIEUDE");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Matinbai");

                    b.ToTable("tin_bai", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
